name: Cypress UI Test

on: 
  push:
    branches:
      - amir
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'  # Ensure this matches the required Node.js version

      - name: Install Root Dependencies
        run: npm ci

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Start the application
        run: |
          cd frontend
          npm run start &
          npx wait-on http://localhost:3000

      - name: Run Cypress tests
        run: |
          cd frontend
          npx cypress run

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos/**

      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**
