name: Cypress Tests

on:
  push:
    branches:
      - amir
  pull_request:
    branches:
      - amir

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: npx cypress install

      - name: Start the application
        run: npm start &
        env:
          NODE_ENV: 'development'
        timeout-minutes: 2

      - name: Wait for server to be ready
        run: sleep 5

      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/integration/gui_spec.js"

      - name: Upload Cypress Artifacts on Failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress Videos on Failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
